### ISSUE TITLE
Use of flush_immediately when used as a standalone logger

### ISSUE THREAD

**Issue by nicholashibberd** [actindi/act-fluent-logger-rails#35]
Hi, 

We are using this gem as a replacement for the default `Rails.logger` and it works great, but we are also using it as a separate logger in the same app, one that we assign to a constant with different tags, and then log to manually.

```ruby
# config/initializers/ui_flow_logger.rb

UI_FLOW_LOGGER = ActFluentLoggerRails::Logger.new ...
```

```ruby
# app/controllers/application_controller.rb

before_filter :log_ui_flow

def log_ui_flow
  UI_FLOW_LOGGER.info({foo: 'bar'}.to_json)
end
```

When using it this way, i.e. outside of the rack request lifecycle, the logs do not get flushed unless we set `flush_immediately` to `true`. Is this the correct technique, or are we missing something?

**Comment by quek** [comment]
It is the correct technique.

**Comment by nicholashibberd** [comment]
Thanks, thanks are you happy for me to PR a change to the docs in case others run into the same issue?

**Comment by quek** [comment]
Yes, please PR.
Thanks

**Comment by nicholashibberd** [comment]
Closing - https://github.com/actindi/act-fluent-logger-rails/pull/36

**Comment by fabirydel** [comment]
@quek Hi, I stumbled upon this long closed issue because I'm switching from using `ActFluentLoggerRails` as my replacement for the default Rails logger alone to also using it a separate logger to log with it manually.
Should I expect a big performance problems in terms of the extra stress this will cause to fluentd and/or in terms of the extra bit of time that now every request will take by flushing immediately every time?
For a bit of context, the app I'm using it on can run 100K requests per hour on peak hours. I'd appreciate any help you can give me, thanks.
